import type { Project } from './types'

export const projects: Project[] = [
  {
    title: 'LegalAgent',
    slug: 'legal-agent',
    description:
      "AI assistant with both voice and chat capabilities into LegalAgent's React Native (Expo) mobile app. This assistant empowers lawyers to swiftly access case information, providing contextual legal support, document summaries, and procedural guidance.",
    tech: [
      'TypeScript',
      'React Native',
      'Expo',
      'OpenAI',
      'AI SDK',
      'TanStack Query',
      'TanStack Form',
      'TanStack Start',
      'Tailwind',
      'LLMs',
      'Redis',
      'ReactJS',
    ],
    type: ['ai', 'contract', 'featured', 'mobile', 'backend', 'fullstack'],
    link: '',
    image: 'https://gaboesquivel.com/images/work/legalagent.png',
    images: [],
    achievements: [
      'Developed a multimodal AI assistant with voice and chat interfaces for a React Native app.',
      'Implemented RAG architecture for contextual legal support and document summarization.',
      'Created an admin dashboard with Microsoft SSO and document management features.',
      'Established a bilingual support system with real-time voice transcription and synthesis.',
    ],
    story: [
      'At LegalAgent, I integrated an AI assistant into their React Native mobile app with both voice and chat interfaces to help lawyers access case information efficiently.',
      "I implemented the Vercel AI SDK for chat functionality and OpenAI's Realtime API for voice features, building a multimodal interface with Tailwind CSS. The assistant uses RAG architecture to provide contextual legal support, document summaries, and procedural guidance in both Spanish and English.",
      'I also developed an internal admin dashboard with TanStack Start, adding Microsoft SSO integration, system prompt management, and document categorization for RAG retrieval. This solution improves legal team productivity and simplifies case file access.',
    ],
  },
  {
    title: 'Opyn',
    slug: 'opyn',
    description:
      'Opyn is a decentralized options protocol on Arbitrum that raised $6.7M Series A funding led by Paradigm. Their main product Squeeth is a notable DeFi-native derivative. I implemented their initial trading interface and data indexing setup for Arbitrum Testnet using Next.js, Ponder, and viem/wagmi.',
    tech: [
      'TypeScript',
      'NextJS',
      'Foundry',
      'Solidity',
      'Viem',
      'Wagmi',
      'Ponder',
      'PostgreSQL',
      'Supabase',
      'ShadcnUI',
      'Tailwind',
      'TanStack Query',
      'Zod',
      'nuqs',
      'EVM',
      'Ethereum',
    ],
    type: ['web3', 'contract', 'featured', 'frontend', 'backend'],
    link: 'https://opyn.co',
    image: 'https://gaboesquivel.com/images/work/opyn.png',
    achievements: [
      'Built trading interface with Next.js 14 and React Server Components',
      'Set up Ponder indexing service with PostgreSQL for chain data',
      'Integrated viem/wagmi for Arbitrum Testnet interactions',
      'Implemented type-safe data validation and state management',
    ],
    story: [
      'At Opyn, I built their trading interface with Next.js 14 and React Server Components. The frontend used shadcn/ui components based on Radix UI primitives with Tailwind CSS styling.',
      'I implemented Ponder for blockchain data indexing, storing data in PostgreSQL via Supabase. Chain interactions were handled through viem/wagmi with Alchemy RPC endpoints.',
      'The implementation prioritized type safety using Zod for schema validation, TanStack Query for data management, and nuqs for URL state handling.',
    ],
  },
  // {
  //   title: 'BasilicEVM',
  //   slug: 'basilic-evm',
  //   description:
  //     'BasilicEVM is a performance-optimized development stack for EVM applications. Built with Foundry, viem/wagmi, and Next.js 15, it features AI-powered development workflows, specialized cursor rules, and streamlined UI generation. The stack includes smart contracts, chain integration, frontend components, and data layer with Ponder indexing.',
  //   tech: [
  //     'TypeScript',
  //     'Solidity',
  //     'Foundry',
  //     'NextJS',
  //     'ReactJS',
  //     'Ponder',
  //     'Postgres',
  //     'Viem',
  //     'Wagmi',
  //     'EVM',
  //     'ThirdWeb',
  //     'Alchemy',
  //     'Ethereum',
  //     'ShadcnUI',
  //     'Tailwind',
  //     'TanStack Query',
  //     'Zod',
  //     'nuqs',
  //     'Supabase',
  //   ],
  //   type: ['web3', 'oss'],
  //   link: 'https://github.com/blockmatic/basilic-evm',
  //   image: 'https://gaboesquivel.com/images/work/basilic-evm.webp',
  //   repo: 'https://github.com/blockmatic/basilic-evm',
  //   achievements: [
  //     'Developed a modular architecture for EVM applications, improving scalability and maintainability.',
  //     'Integrated AI-powered development workflows to optimize smart contract and frontend development.',
  //   ],
  //   story: [
  //     'BasilicEVM emerged from my extensive experience with EVM-based applications and the need for a more streamlined, performance-optimized development stack. The project combines cutting-edge technologies like Foundry, viem/wagmi, and Next.js 15 to create a comprehensive solution for building scalable blockchain applications.',
  //     "By integrating AI-powered development workflows and specialized cursor rules, we've significantly improved developer productivity and code quality. The incorporation of Ponder indexing and Supabase has enabled real-time data processing capabilities, making it easier to build responsive and efficient dApps.",
  //     'The project continues to evolve with community feedback, focusing on maintainability, performance, and developer experience. Our modular architecture ensures that teams can easily adapt and extend the stack to meet their specific needs.',
  //   ],
  // },
  {
    title: 'bitlauncher',
    slug: 'bitlauncher',
    description:
      'BitLauncher is an AI and crypto launchpad platform that provides early access to promising AI unicorn startups through token sales and auctions. It features a batch auction system for token sales, ensuring fair and transparent price discovery. Participants bid during a fixed period, and tokens are distributed at a uniform price, eliminating manipulation and ensuring equal opportunities for all investors.',
    tech: [
      'TypeScript',
      'Solidity',
      'Hardhat',
      'EVM',
      'NextJS',
      'ReactJS',
      'Viem',
      'Wagmi',
      'NodeJS',
      'PostgreSQL',
      'Ethereum',
      'GCP',
      'Docker',
      'Alchemy',
      'Trigger',
      'Supabase',
      'ShadcnUI',
      'Tailwind',
      'TanStack Query',
      'Zod',
      'nuqs',
      'OpenAI',
      'AI SDK',
      'PostgreSQL',
    ],
    type: [
      'web3',
      'ai',
      'oss',
      'full-time',
      'lead',
      'defi',
      'featured',
      'frontend',
      'backend',
      'fullstack',
    ],
    link: 'https://bitlauncher.ai',
    image: 'https://gaboesquivel.com/images/work/bitlauncher.png',
    video: 'https://www.youtube.com/watch?v=U6vn3KOEwcQ',
    repo: 'https://github.com/bitcashorg/smartevm',
    achievements: [
      'Architected a full-stack solution using Viem, Wagmi, Alchemy, Trigger.dev, Supabase, Next.js 14, and ShadcnUI to ensure a scalable and responsive platform.',
      'Crafted a custom token bridge for swapping USDT, USDC, and BITUSD to USDCred tokens, facilitating seamless bidding within the platform.',
      'Implemented a transaction data indexing system with Supabase for efficient querying, real-time subscriptions, and data aggregation analytics.',
      'Deployed Gnosis auction Solidity contracts to EOS EVM and developed a bidding interface with real-time updates via Supabase subscriptions.',
      'Created a wallet interface that displays real-time EVM balances through Wagmi token balance subscriptions and EOS token balances via RPC polling.',
      'Built a custom indexer for EOS EVM using Node.js, Viem EVM event subscriptions, and dFuse stream for EOS.',
      'Developed the chatbot assistant at bitlauncher.ai, leveraging tools integration for accessing the latest news and YouTube videos, and RAG for detailed info retrieval.',
      'Integrated AI SDK for internationalization automation and established an AI-driven development workflow using v0.dev, Anthropic Claude Sonnet, Cursor IDE, and SourceryAI.',
    ],
    story: [
      'BitLauncher is an AI and crypto launchpad platform providing access to AI startups through token sales and auctions. The platform uses a decentralized approach to make the investment process more accessible to participants.',
      'The batch auction system creates a transparent environment for token sales, distributing tokens at a uniform price to reduce barriers in fundraising. I implemented Viem, Wagmi, and Supabase to build a responsive user interface and data layer.',
      "I developed this project with the team behind bitcash.org, with whom I've been working since 2020. The platform facilitates token sales using blockchain technology while maintaining a focus on accessibility.",
    ],
  },
  {
    title: 'Masterbots',
    slug: 'masterbots',
    description:
      'Masterbots.ai is a platform that aims to elevate AI beyond ChatGPT by providing specialized chatbots, social sharing features, and user-friendly innovation. It features domain-specific AI chatbots that can perform more advanced tasks beyond basic information lookup or simple conversations.',
    tech: [
      'NextJS',
      'NodeJS',
      'GraphQL',
      'ReactJS',
      'PostgreSQL',
      'TypeScript',
      'OpenAI',
      'AI SDK',
      'LLMs',
      'Docker',
      'GCP',
      'ShadcnUI',
      'Tailwind',
      'TanStack Query',
      'Zod',
      'nuqs',
      'PostgreSQL',
    ],
    type: ['ai', 'oss', 'featured', 'frontend', 'backend', 'fullstack'],
    link: 'https://masterbots.ai',
    image: 'https://gaboesquivel.com/images/work/masterbots.png',
    repo: 'https://github.com/bitcashorg/masterbots',
    achievements: [
      'Integrated AI SDK for internationalization automation and AI-driven workflow.',
      'Developed specialized AI agents and chatbot interfaces for various use cases.',
      'Set up a scalable Next.js architecture and trained the team for effective implementation.',
      'Integrated AI-driven development workflow using v0.dev, Anthropic Claude Sonnet, Cursor IDE, and SourceryAI.',
    ],
    story: [
      'Masterbots.ai focuses on domain-specific AI chatbots that go beyond basic information retrieval. The platform provides specialized conversational tools designed to handle more complex tasks than standard chatbots.',
      'I integrated AI SDKs and developed specialized agents to enable features like automated internationalization and workflow optimization. These implementations allow the platform to better address diverse user requirements.',
      'This project was built with the same team behind bitcash.org and bitlauncher.ai, continuing our collaborative work in AI and blockchain technologies. The platform combines AI capabilities with practical application design.',
    ],
  },
  {
    title: 'ZTX',
    slug: 'ztx',
    description:
      'ZTX is a web3 metaverse platform backed by Jump Crypto and ZEPETO (a subsidiary of Naver Z Corp with over 200M users). The platform enables creators to build, play, and earn through blockchain-based NFT trading.\n As a software consultant in the early stages of ZTX, I was responsible for developing the react app to host the metaverse and the WebGL/EVM wallet integration.',
    tech: [
      'WebGL',
      'Ethereum',
      'Ethers',
      'NFT',
      'NodeJS',
      'ReactJS',
      'NextJS',
      'AWS',
      'Serverless',
      'Tailwind',
      'TypeScript',
    ],
    type: ['web3', 'full-time', 'featured', 'frontend', 'fullstack'],
    link: 'https://ztx.io',
    image: 'https://gaboesquivel.com/images/work/ztx.png',
    video: 'https://www.youtube.com/watch?v=h58y6UzZ7RA',
    achievements: [
      'Set up the initial React architecture using Next.js, TailwindCSS, and Framer Motion.',
      'Developed a WebGL EVM wallet connector using Ethers.js.',
      'Implemented advanced analytics and reporting using Google Tag Manager.',
    ],
    story: [
      'ZTX is a web3 metaverse platform that enables creators to build, play, and earn in a blockchain-integrated environment. As a software consultant during its early stages, I helped develop the React application hosting the metaverse experience.',
      'I set up the initial architecture using Next.js, TailwindCSS, and Framer Motion to create the application foundation. I also built a WebGL EVM wallet connector with Ethers.js to enable NFT trading functionality within the platform.',
      'The project is backed by Jump Crypto and ZEPETO and focuses on providing creators with blockchain technology integration. My work involved connecting frontend experiences with underlying blockchain capabilities.',
    ],
  },
  {
    title: 'RareMint',
    slug: 'raremint',
    description:
      "RareMint digitizes authenticated real-world sports collectibles as NFTs on the Polygon network, offering fractional ownership and trading of high-value items. The platform partners with professional sports organizations to ensure authenticity.\n I led technical efforts at RareMint to enhance the NFT marketplace's performance and maintainability, including the integration with Polygon network for efficient NFT auctions.",
    tech: [
      'NextJS',
      'EVM',
      'Ethers',
      'NFT',
      'ReactJS',
      'GCP',
      'NodeJS',
      'GraphQL',
      'TypeScript',
      'Ethereum',
      'Docker',
      'Tailwind',
      'PostgreSQL',
    ],
    type: ['web3', 'full-time', 'featured', 'frontend', 'backend', 'fullstack'],
    link: 'https://raremint.com',
    image: 'https://gaboesquivel.com/images/work/raremint.png',
    video: 'https://www.youtube.com/watch?v=2wh32w7N9xg',
    images: ['https://gaboesquivel.com/images/work/raremint-perf.jpeg'],
    achievements: [
      'Built an EVM NFT data indexer using Moralis streams, Node.js, and PostgreSQL.',
      'Refactored the marketplace using RemixRun SSR for improved performance and responsiveness.',
      'Integrated Wallet Connect for secure transactions and improved user experience.',
    ],
    story: [
      'RareMint digitizes real-world sports collectibles as NFTs for a digital collectible experience. As technical lead, I worked on improving the marketplace performance and maintainability.',
      'I built an EVM NFT data indexer using Moralis streams, Node.js, and PostgreSQL for efficient data processing. I also refactored the marketplace using RemixRun SSR to improve performance and responsiveness.',
      'The integration of Wallet Connect improved transaction security and user experience. My work focused on applying blockchain technology to create a functional digital collectibles platform.',
    ],
  },
  {
    title: 'bitcashBank',
    slug: 'bitcashbank',
    description:
      "Bitcash is an established crypto banking platform with over 50,000 users across Latin America, handling millions in transaction volume through its regulated financial infrastructure. The platform integrates with local banking systems in multiple countries and features BitcashDAO for community governance of its decentralized finance products.\n At Bitcash, my role from the start focused on infrastructure design, tech recruitment, and developer training. I later transitioned to a consulting role to guide the platform's continuous adaptation and success.",
    tech: [
      'Antelope',
      'C++',
      'ReactJS',
      'WebAuthN',
      'Biometrics',
      'GCP',
      'NodeJS',
      'GraphQL',
      'PostgreSQL',
      'TypeScript',
      'ShadcnUI',
      'Tailwind',
      'Stitches',
      'Zustand',
    ],
    type: [
      'web3',
      'contract',
      'lead',
      'featured',
      'frontend',
      'backend',
      'fullstack',
      'mobile',
    ],
    link: 'https://bitcash.org',
    image: 'https://gaboesquivel.com/images/work/bitcash-bank.png',
    video: 'https://www.youtube.com/watch?v=2JuHy_w0Ct4',
    repo: 'https://github.com/bitcashorg',
    achievements: [
      'Led infrastructure design and deployment, improving scalability and security.',
      'Built and optimized BitcashDAO for efficient community governance.',
      'Developed robust GraphQL APIs for seamless blockchain data retrieval.',
    ],
    story: [
      'BitcashBank is a platform for cryptocurrency transactions including buying, trading, depositing, and earning. My initial role involved designing the infrastructure, recruiting technical talent, and training developers to build a solid foundation.',
      'As the project progressed, I moved to a consulting role to guide its development. I helped build and optimize BitcashDAO for community-based governance, making the platform more responsive to user requirements.',
      "I developed chaingraph.io for real-time data updates and implemented WebAuthn integration with the EOSIO blockchain to create a 'walletless' experience. This implementation allowed for a progressive web app approach that improved security while avoiding app store constraints.",
    ],
  },
  {
    title: 'Emanate',
    slug: 'emanate',
    description:
      'Emanate is a blockchain-based music platform that raised over $2M in funding and partnered with major artists and labels. The platform features their native EMT token for artist payments and uses smart contracts to ensure transparent royalty distribution.\n At Emanate, I maintained the ReactJS web app streaming platform and developed back-office tools for artist revenue distribution, working with a distributed team across Australia, Europe, and the Americas.',
    tech: ['ReactJS', 'TypeScript', 'EOS', 'AWS', 'Tailwind'],
    type: ['web3', 'contract', 'featured', 'frontend'],
    link: 'https://emanate.live',
    image: 'https://gaboesquivel.com/images/work/emanate.png',
    video: 'https://www.youtube.com/watch?v=qjmn7M7YC9g',
    achievements: [
      'Maintained and optimized the ReactJS streaming platform for improved performance.',
      'Developed back-office tools for efficient artist revenue distribution.',
      'Integrated AWS cloud solutions for enhanced scalability.',
    ],
    story: [
      'Emanate is a Web3 network marketplace for the music industry that streamlines creation, distribution, and monetization. At Emanate, I maintained and optimized the ReactJS web app streaming platform for better performance.',
      'I built back-office tools for artist revenue distribution, enabling more efficient payment processing. The system used blockchain technology to improve transparency and accuracy in financial transactions.',
      'I also integrated AWS cloud solutions to enhance platform scalability for handling increased user activity and data processing. My work focused on applying technology to improve the music distribution process.',
    ],
  },
  {
    title: 'Make Sense Labs',
    slug: 'make-sense-labs',
    description:
      "Sense.chat, developed by Sense/Make Sense Labs (backed by Tim Draper and other notable investors), was one of the first crypto messaging apps to implement self-sovereign identity and encrypted communications on blockchain. The app gained recognition at major tech conferences and blockchain events.\n My role at Sense involved enhancing the React Native app's performance and integrating it with the EOS mainnet for secure messaging and token functionality.",
    tech: ['React Native', 'TypeScript', 'EOS'],
    type: ['web3', 'contract', 'featured', 'mobile'],
    link: 'https://www.youtube.com/watch?v=2DJxzYDaAz8',
    image: 'https://gaboesquivel.com/images/work/sense-chat.png',
    video: 'https://www.youtube.com/watch?v=2DJxzYDaAz8',
    achievements: [
      'Improved app performance and reduced load times by optimizing React Native components.',
      'Integrated EOS mainnet functionalities for secure blockchain-based transactions.',
      'Enhanced security and privacy features for better user protection.',
    ],
    story: [
      'At Make Sense Labs, I worked on Sense.chat, a secure chat and transaction app focusing on user data privacy. I improved the React Native app performance to create a more responsive experience.',
      'I integrated the app with the EOS blockchain mainnet to enable secure transactions and token functionality. The implementation included a built-in wallet and token incentives for communities.',
      "I also enhanced the app's security and privacy features to strengthen user data protection. The work combined mobile app optimization with blockchain integration.",
    ],
  },
  {
    title: 'ChainGraph',
    slug: 'chaingraph',
    description:
      'This real-time GraphQL toolkit is designed for EOSIO/Antelope blockchain applications, offering features like data subscriptions and querying multiple blockchains.\n As a personal side project during my time at Bitcash, I was responsible for the architectural design, technology selection, and coding of the toolkit, including a real-time blockchain data streaming package.',
    tech: [
      'Antelope',
      'NodeJS',
      'Docker',
      'GraphQL',
      'GCP',
      'RXJS',
      'Docker',
      'TypeScript',
      'PostgreSQL',
    ],
    type: ['web3', 'oss', 'featured', 'backend'],
    link: 'https://chaingraph.io',
    image: 'https://gaboesquivel.com/images/work/chaingraph.png',
    repo: 'https://github.com/blockmatic/chaingraph',
    achievements: [
      'Developed a real-time GraphQL subscription toolkit for EOSIO/Antelope blockchains.',
      'Implemented blockchain data indexing and event streaming capabilities.',
      'Designed an intuitive developer interface for querying multiple blockchain networks.',
    ],
    story: [
      'ChainGraph is a real-time GraphQL toolkit for EOSIO/Antelope blockchain applications. It provides tools for data subscriptions and querying across multiple blockchains.',
      'As a personal side project while working at Bitcash, I handled the architectural design, technology selection, and implementation. This included building a real-time blockchain data streaming package for data access.',
      'The project is open-source and serves as a resource for developers working with EOSIO/Antelope blockchains. It addresses common data access challenges faced when working with these blockchain technologies.',
    ],
  },
  {
    title: 'EOS Costa Rica',
    slug: 'eos-costa-rica',
    description:
      'EOS Costa Rica is a leading block producer and infrastructure provider for EOSIO/Antelope blockchains, maintaining critical network nodes and developing custom blockchain solutions. The company is recognized for its contributions to the EOS mainnet and enterprise blockchain implementations.\n Joining EOS Costa Rica at its inception, I played a key role in the EOS mainnet launch, managed validators for multiple networks, and helped establish the custom development services division. My major contribution included leading the architecture for a custom private blockchain for Grant Thornton.',
    tech: [
      'EOS',
      'C++',
      'PostgreSQL',
      'NodeJS',
      'GraphQL',
      'ReactJS',
      'Tailwind',
      'GCP',
      'Azure',
      'Docker',
      'Terraform',
      'NodeJS',
      'TypeScript',
    ],
    type: [
      'web3',
      'full-time',
      'lead',
      'featured',
      'frontend',
      'backend',
      'fullstack',
    ],
    link: 'https://eoscostarica.io',
    image: 'https://gaboesquivel.com/images/work/eoscostarica.png',
    repo: 'https://github.com/eoscostarica',
    video: 'https://www.youtube.com/watch?v=-1y0fGs8Xgw&',
    achievements: [
      'Played a key role in the EOS mainnet launch, ensuring network stability and security.',
      'Led the development of a custom private blockchain for Grant Thornton.',
      'Managed validator nodes across multiple EOSIO-based networks.',
    ],
    story: [
      'Joining EOS Costa Rica at its inception, I helped launch the EOS mainnet and managed validator nodes across multiple EOSIO-based networks to maintain blockchain stability and security.',
      "As main architect and tech lead, I built a team and designed the architecture for Grant Thornton's custom private blockchain using Azure, Terraform, EOSIO, and a React client. This implementation provided an enterprise blockchain solution tailored to specific requirements.",
      'I also managed open source software development and developer relations to build community engagement. My work at EOS Costa Rica included establishing the custom development services division and expanding technical capabilities within the organization.',
    ],
  },
  {
    title: 'EOS Rate',
    slug: 'eos-rate',
    description:
      'EOS Rate is a community-driven tool for rating EOS Block Producers, featuring a radial graph and community input stored on the blockchain.\n In this project, I was responsible for the technical architecture and selecting the appropriate technology.',
    tech: [
      'EOS',
      'C++',
      'GraphQL',
      'ReactJS',
      'GCP',
      'Docker',
      'TypeScript',
      'PostgreSQL',
    ],
    type: ['web3', 'oss', 'featured', 'frontend', 'backend', 'fullstack'],
    link: 'https://eosrate.io',
    image: 'https://gaboesquivel.com/images/work/eosrate.png',
    repo: 'https://github.com/eoscostarica/eos-rate',
    video: 'https://www.youtube.com/watch?v=saZnZqJsMhk',
    achievements: [
      'Designed and implemented a decentralized rating system for EOS Block Producers.',
      'Built an intuitive radial graph interface to visualize community ratings.',
      'Developed a GraphQL API for seamless data retrieval and user interaction.',
    ],
    story: [
      'EOS Rate is a community-driven tool for rating EOS Block Producers, using a radial graph interface and storing ratings on the blockchain. The tool promotes transparency and accountability in the EOS ecosystem.',
      'I was responsible for designing the technical architecture and selecting appropriate technologies to build a robust platform. The implementation includes a decentralized rating system with an intuitive visualization interface.',
      'The project combines blockchain technology with user-centered design to create a practical tool for the community. EOS Rate provides a resource for EOS participants to make more informed decisions about Block Producers based on community ratings.',
    ],
  },
  {
    title: 'Fantasy Top Shots',
    slug: 'fantasy-top-shots',
    description:
      "This mobile app game built on NBA Top Shot NFTs was developed for the 2022 Flow Hackathon. It integrates with NBA Top Shot's marketplace, which has processed over $1B in NFT transactions and is officially licensed by the NBA. The game received recognition at the Flow Hackathon among hundreds of participating projects.\n My contribution to this project was in the game's design and development, utilizing my skills in blockchain technology and mobile app development.",
    tech: ['Flow', 'NFT', 'ReactJS', 'Expo', 'Tailwind', 'TypeScript'],
    type: ['web3', 'hackathon', 'featured', 'mobile'],
    link: 'https://fantasy-top-shot.vercel.app',
    image: 'https://gaboesquivel.com/images/work/fantasy-top-shots.png',
    video: 'https://www.youtube.com/watch?v=Il2aiKhy_ug',
    repo: 'https://github.com/bitcashorg/fantasy-top-shot',
    achievements: [
      'Designed and developed the mobile game using Flow blockchain technology.',
      'Integrated NBA Top Shot NFTs for an immersive gaming experience.',
      'Implemented responsive UI and smooth gameplay mechanics using React Native and Expo.',
    ],
    story: [
      'Fantasy Top Shots was built for the 2022 Flow Hackathon as a mobile game using NBA Top Shot NFTs. The game allows users to utilize their NFT collections in a fantasy sports format.',
      'My role included both design and development, applying blockchain and mobile app development skills. The implementation uses Flow blockchain for NFT transaction handling within the game experience.',
      'This collaborative project with the Bitlauncher team explores the intersection of blockchain technology and mobile gaming. It provides NFT owners with additional utility for their digital assets through practical gameplay mechanics.',
    ],
  },
  {
    title: 'Substrate Contracts UI',
    slug: 'substrate-contracts-ui',
    description:
      'Substrate Contracts UI is a key developer tool maintained by Parity Technologies (founded by Ethereum co-founder Dr. Gavin Wood) for the Polkadot ecosystem, which has a market cap exceeding $7B. The UI simplifies WASM smart contract deployment and interaction on Substrate-based blockchains used by dozens of major projects.\n I contributed to the project by enhancing code quality through multiple open-source contributions and gained experience in building dApps with Substrate.',
    tech: ['Polkadot', 'Substrate', 'ReactJS', 'Tailwind', 'TypeScript'],
    type: ['web3', 'oss', 'frontend'],
    link: 'https://contracts-ui.substrate.io/',
    image: 'https://gaboesquivel.com/images/work/contracts-ui.png',
    repo: 'https://github.com/paritytech/contracts-ui',
    achievements: [
      'Enhanced code quality and performance through multiple open-source contributions.',
      'Developed UI components for seamless interaction with WASM smart contracts.',
      'Gained extensive experience in building dApps on the Substrate framework.',
    ],
    story: [
      'Substrate Contracts UI is a web application for deploying and interacting with WASM smart contracts on Substrate blockchains. I contributed to the project by making open-source improvements to enhance code quality and performance.',
      'I developed UI components for interacting with WASM smart contracts to improve usability and efficiency. This work provided practical experience in building decentralized applications on the Substrate framework.',
      "I made these contributions while learning about Polkadot's ecosystem and exploring their protocol and smart contract development. The project demonstrates open-source contribution to blockchain developer tooling and complements my experience with other blockchain technologies.",
    ],
  },
  {
    title: 'Wizard World',
    slug: 'wizard-world',
    description:
      "Wizart.world is a groundbreaking platform at the intersection of AI and blockchain that connects to OpenAI's DALL-E models to generate AI images and mint them as NFTs on the Flow blockchain. Developed during the Flow Hackathon 2022, the project was among the first to combine generative AI with blockchain-based ownership rights for digital art.\n My role involved the app's development, focusing on integrating OpenAI's models for image generation and ensuring smooth functionality with the Flow blockchain through Niftory's NFT infrastructure.",
    tech: [
      'NextJS',
      'ReactJS',
      'Flow',
      'Niftory',
      'Dalle',
      'OpenAI',
      'Tailwind',
      'NFT',
      'TypeScript',
    ],
    type: ['ai', 'web3', 'hackathon', 'featured', 'frontend'],
    link: 'https://wizart.world',
    image: 'https://gaboesquivel.com/images/work/wizart-world.png',
    video: 'https://www.youtube.com/watch?v=I_vBUflXHFA',
    repo: 'https://github.com/bitcashorg/wizartworld',
    achievements: [
      'Developed a progressive web app integrating AI-generated images with blockchain minting.',
      "Implemented OpenAI's LLM models for AI-driven image creation and metadata processing.",
      'Integrated the Flow blockchain for seamless NFT minting and storage.',
    ],
    story: [
      "Wizard World is a progressive web app that connects to OpenAI's LLM models to generate AI images and mint them on the Flow blockchain. We developed it for the Flow Hackathon 2022 with the Bitlauncher team.",
      "I worked on the app development, focusing on integrating OpenAI's models for image generation and implementing Flow blockchain functionality. The integration enables users to create images with AI and mint them as NFTs in a streamlined process.",
      'The project combines AI and blockchain technologies to create a practical application for digital content creation. It demonstrates how AI-generated art can be incorporated into blockchain-based ownership systems.',
    ],
  },
  {
    title: 'dBoard',
    slug: 'dboard',
    description:
      'dBoard is a DAO decision-making and community management tool. It allows stakeholders to strategize, debate, and vote on actions for organizational efficiency.\n In this project, my contributions included overseeing the technical architecture and the smart contract development and integration on the webapp.',
    tech: [
      'Antelope',
      'NextJS',
      'ReactJS',
      'GCP',
      'GraphQL',
      'TypeScript',
      'Docker',
      'PostgreSQL',
    ],
    type: ['web3', 'oss', 'frontend', 'backend', 'fullstack'],
    link: 'https://eos.dboard.ai',
    image: 'https://gaboesquivel.com/images/work/dboard.png',
    repo: 'https://github.com/bitcashorg/bitcash-contract-dho',
    achievements: [
      'Led the technical architecture for DAO governance and decision-making.',
      'Developed and integrated smart contracts to enhance community voting mechanisms.',
      'Implemented a seamless GraphQL API for improved data interactions.',
    ],
    story: [
      'dBoard is a DAO decision-making and community management tool that allows stakeholders to strategize, debate, and vote on organizational actions. I oversaw the technical architecture and led smart contract development and integration.',
      'The implementation uses Antelope blockchain and Next.js to create a decentralized governance platform. The smart contracts provide secure and transparent community voting mechanisms to enhance trust among participants.',
      'I built a GraphQL API to improve data access and analysis for stakeholders. The project focuses on providing practical tools for DAOs to operate more efficiently and make collective decisions.',
    ],
  },
  {
    title: 'Knowledge.io',
    slug: 'knowledge-io',
    description:
      'Knowledge.io was one of the first blockchain platforms aimed at knowledge-sharing with a token-based reward system. The project successfully completed its ICO in 2018, raising funds to build a decentralized knowledge ecosystem that included partnerships with advertising networks to monetize user expertise.\n My role at Knowledge included leading the architecture of the Ethereum-based token and supporting systems for their successful ICO, and forming a skilled development team across three countries.',
    tech: [
      'TypeScript',
      'Ethereum',
      'Ethers',
      'Solidity',
      'AWS',
      'Serverless',
      'GraphQL',
      'React Native',
      'ReactJS',
      'NodeJS',
      'EVM',
      'PostgreSQL',
    ],
    type: ['web3', 'contract', 'oss', 'frontend', 'backend', 'fullstack'],
    link: 'https://github.com/knowledge/ethereum-contracts',
    image: 'https://gaboesquivel.com/images/work/knowledge.png',
    repo: 'https://github.com/knowledge',
    achievements: [
      "Led the development and deployment of Knowledge.io's token system.",
      'Designed and implemented smart contracts for token rewards and transactions.',
      "Built a scalable serverless infrastructure to support the platform's growth.",
    ],
    story: [
      'Knowledge is a platform that rewards users for sharing information through a token system. My role included leading the architecture of the token and supporting systems for a successful ICO.',
      'I designed and implemented smart contracts for token rewards and transactions to create a secure and efficient system. I also built a serverless infrastructure using AWS to support the platform operations.',
      'I formed a development team with the necessary technical skills to implement the project requirements. The work focused on applying blockchain technology to create a functional token-based incentive system.',
    ],
  },
  {
    title: 'Wink',
    slug: 'wink',
    description:
      "Wink, Costa Rica's first neo-bank, offers a mobile app for online banking, eliminating the need for physical branch visits.\n I developed the first version of Wink's mobile app and backend services within AWS. My role involved API integration with partner banks and forming a dedicated development team.",
    tech: [
      'TypeScript',
      'AWS',
      'Serverless',
      'React Native',
      'ReactJS',
      'NodeJS',
      'Biometrics',
      'Docker',
    ],
    type: [
      'full-time',
      'lead',
      'featured',
      'mobile',
      'backend',
      'fullstack',
      'frontend',
    ],
    link: 'https://holawink.com',
    image: 'https://gaboesquivel.com/images/work/wink.png',
    video: 'https://www.youtube.com/watch?v=rfeISMW_OVc',
    achievements: [
      "Developed the first version of Wink's mobile banking app.",
      'Integrated API connections with partner banks for seamless transactions.',
      'Designed and implemented biometric authentication for enhanced security.',
    ],
    story: [
      "Wink is Costa Rica's first neo-bank, offering a mobile app for online banking without physical branch visits. I developed the first version of their mobile app and backend services within AWS.",
      'My responsibilities included technology selection, project planning, and coordinating API integration with partner banks. I implemented biometric authentication to enhance security while keeping the user experience streamlined.',
      'The project required forming a development team with the necessary skills to implement the technical requirements. This work applied mobile and cloud technologies to create a digital banking solution for the Costa Rican market.',
    ],
  },
  {
    title: 'American Express',
    slug: 'american-express',
    description:
      "American Express, a Fortune 100 company with over 100M cardmembers globally and $180B+ in annual revenue, operates one of the world's largest payment networks. Their website serves millions of users daily for account management and financial services.\n My responsibility was focused on front-end development, including Object-Oriented JavaScript, AJAX for a fluid user experience, and implementing A/B Testing and usage analytics.",
    image: 'https://gaboesquivel.com/images/work/amex.jpg',
    link: 'https://www.americanexpress.com/',
    tech: [
      'JSP (Struts)',
      'Omniture',
      'Adobe mBox',
      'Facebook API',
      'Dojo',
      'jQuery',
      'CSS',
    ],
    type: ['full-time', 'featured', 'frontend'],
    achievements: [
      'Enhanced user experience through AJAX-driven interactivity.',
      'Implemented A/B testing strategies to optimize user engagement.',
      'Developed analytics integrations to track usage and improve performance.',
    ],
    story: [
      'At American Express, I worked on front-end development for their website where cardmembers manage financial accounts. I used Object-Oriented JavaScript and AJAX techniques to create a responsive user experience.',
      'I implemented A/B testing to optimize engagement and integrated analytics for tracking usage patterns and performance. This work required understanding user needs and translating them into functional interfaces.',
      'The project involved contributing to a financial platform used by millions of cardmembers daily. My development work focused on making account management more intuitive and accessible through the web interface.',
    ],
  },
  {
    title: 'AMEX Money Talk',
    slug: 'amex-money-talk',
    description:
      "The National Money Night Talk by American Express aimed to promote financial communication between parents and teenagers.\n As a Frontend Engineer, I developed the campaign's landing page, focusing on user engagement and information delivery.",
    link: 'https://www.youtube.com/watch?v=a2vDoYyXIJQ',
    image: 'https://gaboesquivel.com/images/work/money-talk.jpg',
    tech: ['JavaScript', 'CSS'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed an engaging landing page to enhance user interaction.',
      'Implemented responsive design for a seamless experience across devices.',
      'Optimized page performance to improve load times and accessibility.',
    ],
    story: [
      "The National Money Night Talk by American Express promoted financial communication between parents and teenagers. As a Frontend Engineer, I developed the campaign's landing page focusing on user engagement and information delivery.",
      'I created a user-friendly interface with easy navigation and interaction features. The implementation used responsive design techniques to provide consistent experiences across different devices.',
      "The project supported American Express's financial literacy initiative for families. The landing page needed to effectively present information while encouraging participation in the campaign.",
    ],
  },
  {
    title: 'Elder Scrolls Online',
    slug: 'elder-scrolls-online',
    description:
      'Elder Scrolls Online, developed by ZeniMax Online Studios and published by Bethesda Softworks, is a massively multiplayer online game with over 20 million players. The official website serves as a central hub for this large gaming community, offering news, game guides, and forums.\n My role was to ensure a user-centric design for the website, facilitating easy navigation and engagement with the content for millions of monthly visitors.',
    tech: ['PHP', 'JavaScript', 'jQuery', 'Facebook API', 'Twitter API'],
    type: ['contract', 'featured', 'frontend'],
    link: 'http://elderscrollsonline.com',
    image: 'https://gaboesquivel.com/images/work/elder-scrolls.jpg',
    achievements: [
      'Designed and implemented a user-centric website for the gaming community.',
      'Optimized site navigation for a seamless user experience.',
      'Integrated social media features to enhance community engagement.',
    ],
    story: [
      'The official website serves as a central hub for a gaming community, offering news, game guides, and forums. My role was to ensure a user-centric design for the website, facilitating easy navigation and engagement with the content.',
      'I worked on balancing visual design with functionality to meet the needs of the gaming community. This included optimizing navigation paths and integrating social media features to improve user experience.',
      'The project required understanding gaming community needs and developing appropriate web interfaces. The implementation created an online space where players could access information and connect with others in the community.',
    ],
  },
  {
    title: 'AMC Yeah TV Facebook App',
    slug: 'amc-yeah-tv-facebook-app',
    description:
      'An online movie streaming service allows watching movies in chapters with detailed information and interactive games.\n I was responsible for the frontend architecture design, integrating the game app with Facebook and the backoffice system with Brightcove web services for video streaming and editing.',
    tech: [
      'PHP',
      'Facebook API',
      'AJAX',
      'Handlebars',
      'Brightcove API',
      'require.js',
      'CSS',
    ],
    type: ['full-time', 'lead', 'featured', 'frontend'],
    link: 'http://yeahtv.com',
    image: 'https://gaboesquivel.com/images/work/yeahtv.jpg',
    achievements: [
      'Designed and built a scalable frontend architecture for an interactive movie experience.',
      'Integrated Brightcove video streaming API for seamless movie playback.',
      'Implemented Facebook API features for user engagement and monetization.',
    ],
    story: [
      'An online movie streaming service allows watching movies in chapters with detailed information and interactive games. I was responsible for the frontend architecture design, integrating the game app with Facebook and the backoffice system with Brightcove web services for video streaming and editing.',
      'I built a scalable and interactive platform that focused on user engagement through video playback and social features. The implementation used the Brightcove API for streaming functionality and content management.',
      "The project combined entertainment content with technical features to create an interactive viewing experience. The integration with Facebook's platform allowed for social sharing and user identification within the application.",
    ],
  },
  {
    title: 'Tikr',
    slug: 'tikr',
    description:
      'Tikr is an online store with dynamic, real-time fluctuating prices, offering a unique shopping experience. It operates on the Ruby on Rails-based Spree backend framework.\n My role at Tikr encompassed full-stack development with a focus on frontend development and customization of the Spree backend framework.',
    link: 'http://tikr.com',
    image: 'https://gaboesquivel.com/images/work/tikr.jpg',
    type: ['contract', 'featured', 'frontend'],
    tech: ['Ruby on Rails', 'Spree', 'Heroku', 'Postgres', 'jQuery', 'SASS'],
    achievements: [
      'Developed a dynamic pricing engine using Spree and Ruby on Rails.',
      'Implemented a real-time price fluctuation system for enhanced user engagement.',
      'Optimized backend performance on Heroku with PostgreSQL integration.',
    ],
    story: [
      'Tikr is an online store with dynamic, real-time fluctuating prices, offering a unique shopping experience. It operates on the Ruby on Rails-based Spree backend framework. My role at Tikr encompassed full-stack development with a focus on frontend development and customization of the Spree backend.',
      'I built a dynamic pricing engine using Spree and Ruby on Rails that enabled real-time price changes. This feature created a more interactive shopping experience for users.',
      'The implementation included optimizing backend performance on Heroku with PostgreSQL database integration. The work combined e-commerce fundamentals with custom pricing mechanisms to create a distinctive online shopping platform.',
    ],
  },
  {
    title: 'Eat Arcade',
    slug: 'eat-arcade',
    description:
      "I designed and developed an SMS subscription system featuring curated dishes from New York City's finest restaurants. The system offered a unique dining experience through mobile technology.\n My responsibilities covered the entire development process, from system design to implementation.",
    tech: [
      'NodeJS',
      'AngularJS',
      'MongoDB',
      'Heroku',
      'Bootstrap',
      'Stripe',
      'Twilio',
      'CSS',
      'Lodash',
    ],
    type: ['contract', 'frontend'],
    link: 'http://www.eatarcade.com/',
    image: 'https://gaboesquivel.com/images/work/eatarcade.jpg',
    achievements: [
      'Designed and built an SMS-based subscription system for restaurant promotions.',
      'Integrated Twilio for seamless messaging and user engagement.',
      'Developed a full-stack solution using Node.js, MongoDB, and AngularJS.',
    ],
    story: [
      "I developed an SMS subscription system for curated dishes from New York City's restaurants. The system provided a direct connection between diners and restaurant offerings via mobile technology.",
      'I built the application using Node.js, Express.js, and AngularJS, integrating Twilio for text messaging functionality. Users received restaurant recommendations through SMS, making discovery more accessible.',
      'The implementation included Stripe for payment processing and Heroku for hosting and scalability. This project combined mobile messaging with restaurant promotion to create a unique food discovery service.',
    ],
  },
  {
    title: 'Jockey Hollow Bar and Kitchen',
    slug: 'jockey-hollow-bar-and-kitchen',
    description:
      "Jockey Hollow Bar and Kitchen, located in Morristown's historic Vail Mansion (built 1917), is a renowned multi-concept restaurant by acclaimed restaurateur Chris Cannon. The venue features The Oyster Bar, The Vail Bar, The Dining Room, and The Rathskeller, earning recognition from The New York Times and other major publications.\n My work focused on developing the main responsive landing page, ensuring an inviting and informative digital gateway to the restaurant's offerings.",
    tech: [
      'SASS',
      'jQuery',
      'Lodash',
      'Grapnel.js',
      'Grunt',
      'NodeJS',
      'Heroku',
      'Divshot',
    ],
    type: ['contract', 'frontend'],
    link: 'http://www.jockeyhollowbarandkitchen.com/',
    image: 'https://gaboesquivel.com/images/work/jockey-hollow.png',
    achievements: [
      'Developed a fully responsive landing page with a focus on user experience.',
      'Optimized page speed and performance for seamless navigation.',
      "Integrated dynamic content features to showcase the restaurant's offerings effectively.",
    ],
    story: [
      "Jockey Hollow Bar and Kitchen, located in a historic mansion, features four distinct dining concepts. I developed their responsive landing page as an informative gateway to the restaurant's offerings.",
      "I built a user-friendly interface that highlighted the venue's unique features and dining options. The implementation focused on performance optimization to ensure smooth navigation and exploration.",
      "The page included dynamic content areas to showcase menus and events effectively. My development work created a functional online presence that accurately represented the restaurant's physical spaces and dining options.",
    ],
  },

  {
    title: 'Jockey Hollow Bar and Kitchen Menu Kiosk App',
    slug: 'jockey-hollow-bar-and-kitchen-menu-kiosk-app',
    description:
      'At Jockey Hollow Bar & Kitchen, I developed the Menu Kiosk App, a responsive web application for tablet kiosks. It simplifies menu selection for patrons and uses Google Spreadsheets for easy updates.\n As the sole developer, my role involved creating an intuitive and efficient digital menu solution, enhancing the dining experience.',
    tech: [
      'SASS',
      'jQuery',
      'Lodash',
      'Grapnel.js',
      'Grunt',
      'NodeJS',
      'Heroku',
      'Divshot',
    ],
    type: ['contract', 'frontend'],
    link: '#',
    image: 'https://gaboesquivel.com/images/work/jockey-hollow-menu.png',
    achievements: [
      'Developed a user-friendly menu kiosk app to enhance restaurant service.',
      'Integrated Google Spreadsheets for seamless menu updates.',
      'Optimized app performance for smooth operation on tablet devices.',
    ],
    story: [
      'At Jockey Hollow Bar & Kitchen, I developed the Menu Kiosk App, a responsive web application for tablet kiosks. It simplifies menu selection for patrons and uses Google Spreadsheets for easy updates.',
      'The app integrates with Google Spreadsheets for real-time menu management, allowing staff to keep information current and accurate. This implementation addresses the frequent menu changes common in restaurants.',
      'As the sole developer, I created an intuitive interface optimized for tablet performance. The kiosk application streamlined the dining experience while providing an efficient solution for displaying menu items.',
    ],
  },
  {
    title: 'Bureau of Trade (Beta)',
    slug: 'bureau-of-trade-beta',
    description:
      "Bureau of Trade (Beta) is an online store offering a range of products, with a frontend integrated with eBay's API for diverse shopping experiences.\n As the sole Fullstack developer, my focus was on frontend development, responsive design, and animations, along with eBay API integration.",
    link: 'http://www.gridium.com/products/portfolio-manager/',
    image: 'https://gaboesquivel.com/images/work/bureau-of-trade.jpg',
    tech: ['PHP', 'eBay API', 'AJAX', 'jQuery', 'CSS'],
    type: ['contract', 'frontend'],
    achievements: [
      "Built a responsive e-commerce frontend integrated with eBay's API.",
      'Developed advanced UI animations for enhanced user experience.',
      'Optimized site performance for faster product browsing.',
    ],
    story: [
      "Bureau of Trade (Beta) is an online store offering a range of products, with a frontend integrated with eBay's API for diverse shopping experiences. As the sole Fullstack developer, my focus was on frontend development, responsive design, and animations, along with eBay API integration.",
      'I built UI animations to enhance user interaction while ensuring the platform remained functional. The eBay API integration expanded product availability without requiring direct inventory management.',
      'The implementation included performance optimization for faster product browsing and page transitions. My work centered on creating a responsive e-commerce interface that could handle product data from external APIs effectively.',
    ],
  },
  {
    title: 'Tractor Supply',
    slug: 'tractor-supply',
    description:
      "Tractor Supply Company, a Fortune 500 company with over 2,000 stores and $10B+ in annual revenue, is America's largest rural lifestyle retailer. Their mobile app serves millions of customers with features like product browsing, exclusive offers, account management, and augmented reality product previews.\n As a consultant, I enhanced the app's performance and code quality, and developed its augmented reality feature, improving user experience and engagement.",
    tech: [
      'React Native',
      'ReactJS',
      'NodeJS',
      'TypeScript',
      'ViroAR',
      'CSS',
      'Redux',
    ],
    type: ['contract', 'mobile'],
    link: 'https://www.tractorsupply.com/tsc/cms/app',
    image: 'https://gaboesquivel.com/images/work/tractor-supply.png',
    achievements: [
      'Enhanced app performance and code quality for a smoother user experience.',
      'Developed an augmented reality feature to preview products interactively.',
      'Implemented TypeScript for improved maintainability and scalability.',
    ],
    story: [
      "The Tractor Supply mobile app offers features like product browsing, exclusive offers, account management, and an augmented reality feature for product previews. As a consultant, I enhanced the app's performance and code quality, and developed its augmented reality feature, improving user experience and engagement.",
      'I implemented TypeScript to improve code maintainability and scalability, ensuring the app could adapt to future requirements. My work focused on technical improvements and feature development for their existing React Native application.',
    ],
  },
  {
    title: 'Photo and Go',
    slug: 'photo-and-go',
    description:
      'MyPhoto.com is an online platform for creating personalized photo products. I led the development of an innovative photo editor app and backend services integrated with existing e-commerce systems.\n My leadership role encompassed technical direction and execution, focusing on creating a smooth and intuitive user experience.',
    tech: ['ReactJS', 'NodeJS', 'Redux', 'AWS', 'Docker', 'PostgreSQL'],
    type: ['contract', 'frontend', 'backend', 'fullstack'],
    link: 'https://www.myphoto.com/',
    image: 'https://gaboesquivel.com/images/work/photoandgo.jpg',
    achievements: [
      'Developed a photo editor app with seamless e-commerce integration.',
      'Led technical execution, ensuring a smooth and intuitive user experience.',
      'Implemented AWS infrastructure for scalable cloud storage and processing.',
    ],
    story: [
      'MyPhoto.com is an online platform for creating personalized photo products. I led the development of an innovative photo editor app and backend services integrated with existing e-commerce systems.',
      'My leadership role encompassed technical direction and execution, focusing on creating a smooth and intuitive user experience. I built the photo editor application with seamless e-commerce integration and implemented AWS infrastructure for cloud storage and image processing.',
      'The project required balancing technical requirements with usability considerations for customers creating custom photo products. My work delivered a functional photo customization solution integrated with e-commerce capabilities.',
    ],
  },
  {
    title: '4Tius Fitness Data Tracker',
    slug: '4tius-fitness-data-tracker',
    description:
      'The 4Tius app is a centralized platform for monitoring fitness data, integrating with Fitbit. It includes a web dashboard and API.\n As a Fullstack software engineer, I led the development of both the web application and backend systems, ensuring seamless integration and user-friendly functionality.',
    tech: ['NodeJS', 'AWS', 'MongoDB', 'AngularJS'],
    type: ['contract', 'frontend', 'backend', 'fullstack'],
    link: 'https://example.com/18techs',
    image: 'https://gaboesquivel.com/images/work/4tius.jpg',
    achievements: [
      'Designed and developed a fitness data tracking system with Fitbit integration.',
      'Built a responsive web dashboard for real-time analytics and monitoring.',
      'Implemented secure API endpoints for efficient data communication.',
    ],
    story: [
      'The 4Tius app is a centralized platform for monitoring fitness data, integrating with Fitbit. It includes a web dashboard and API. As a Fullstack software engineer, I led the development of both the web application and backend systems, ensuring seamless integration and user-friendly functionality.',
      'I designed a responsive web dashboard for real-time fitness analytics and monitoring, allowing users to track their progress effectively. The Fitbit integration ensured accurate and current data throughout the application.',
      'The implementation included secure API endpoints for efficient communication between the app and fitness devices. The project focused on making fitness data more accessible and actionable for users through technology.',
    ],
  },
  {
    title: 'SunTrust',
    slug: 'suntrust',
    description:
      "SunTrust (now Truist after merging with BB&T), was a major financial institution with over $220B in assets serving 4.5M+ households. Their Solid Salutes campaign was a key digital initiative to strengthen community engagement and brand loyalty.\n I developed the entire campaign website, focusing on design and user interaction. My role included overseeing the website's development from concept to implementation, emphasizing user engagement and visual appeal.",
    link: '#',
    image: 'https://gaboesquivel.com/images/work/suntrust-1.jpg',
    tech: ['JavaScript', 'CSS'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed an interactive campaign website for user-generated content.',
      'Optimized website performance for increased user engagement.',
      'Implemented visually appealing UI/UX elements to enhance storytelling.',
    ],
    story: [
      "SunTrust's Solid Salutes campaign facilitated user-generated custom video salutes. I developed the entire campaign website, focusing on design and user interaction.",
      "My role included overseeing the website's development from concept to implementation, ensuring visual appeal and seamless user interaction. I optimized performance to handle expected traffic and improve engagement.",
      'The project required creating a platform that encouraged participation while maintaining brand consistency. The implementation enabled users to create and share personalized content within the campaign framework.',
    ],
  },

  {
    title: 'ScotiaTico',
    slug: 'scotiatico',
    description:
      'Scotiabank, a top 5 Canadian bank with over $1T in assets and operations in 50+ countries, maintains a significant presence in Costa Rica through its ScotiaBank Costa Rica division. Their customer communication initiatives are critical to maintaining their 25M+ global customer relationships.\n I developed the ScotiaTico newsletter, a key communication tool for bank updates and information. My responsibility was crafting an engaging and informative newsletter layout, enhancing communication between the bank and its customers.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/scotiatico.jpg',
    tech: ['JavaScript', 'CSS', 'Wordpress'],
    type: ['other', 'frontend'],
    achievements: [
      'Designed and developed an interactive newsletter layout for ScotiaBank.',
      'Enhanced customer engagement with visually appealing and responsive design.',
      'Implemented Wordpress CMS for easy content management and updates.',
    ],
    story: [
      'For ScotiaBank Costa Rica, I developed the ScotiaTico newsletter, a communication tool for bank updates and information. My responsibility was crafting an engaging and informative newsletter layout, enhancing communication between the bank and its customers.',
      'I focused on creating a visually appealing and responsive design to improve customer engagement and ensure cross-device accessibility. This project was completed while working at IntergraphiDesign, my first development job.',
      'The implementation used Wordpress CMS for easy content management and updates, allowing the bank to efficiently maintain the newsletter. The project applied web development skills to create a practical communication tool for a financial institution.',
    ],
  },
  {
    title: 'Staples',
    slug: 'staples',
    description:
      "Staples, a Fortune 500 company with over $20B in annual revenue, is one of the world's largest office supply retailers with 1000+ stores and a major e-commerce presence serving millions of customers. Their website processes billions in online sales annually.\n My role as a frontend developer involved creating user-friendly and efficient navigation elements, contributing to the overall user experience on their e-commerce platform.",
    link: '#',
    image: 'https://gaboesquivel.com/images/work/staples.jpg',
    tech: ['JavaScript', 'CSS', 'Mootools'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed responsive UI components for improved website accessibility.',
      'Enhanced navigation for a seamless shopping experience.',
      'Optimized front-end performance for faster load times.',
    ],
    story: [
      'At Staples, a retail store for office supplies, I worked on building responsive features and the main website navigation. My role as a frontend developer involved creating user-friendly and efficient navigation elements, contributing to the overall user experience on the website.',
      'I developed responsive UI components to improve accessibility across different devices and screen sizes. The work included performance optimization to reduce load times and enhance usability.',
      'This freelance project required applying web development skills to improve an established e-commerce platform. The implementation focused on practical improvements to navigation and responsive design.',
    ],
  },
  {
    title: 'Gridium',
    slug: 'gridium',
    description:
      'Gridium is a recognized provider of energy analytics software for commercial buildings, helping facility managers optimize energy usage and reduce costs through data-driven insights. Their platform processes data from thousands of buildings to identify savings opportunities.\n I built the first version of the application, focusing on displaying data collected from various buildings.',
    link: 'https://gridium.com/',
    image: 'https://gaboesquivel.com/images/work/gridium.png',
    tech: ['JavaScript', 'Data Charts', 'CSS', 'Bootstrap', 'Heroku'],
    type: ['contract', 'frontend'],
    achievements: [
      'Developed a data visualization platform for energy consumption analytics.',
      'Implemented interactive charts for real-time energy monitoring.',
      'Optimized UI/UX for better readability and user engagement.',
    ],
    story: [
      'Gridium is an energy data analytics prototype for visualizing and analyzing energy consumption. It aids in informed energy management decisions. I built the first version of the application, focusing on displaying data collected from various buildings.',
      'The implementation included interactive charts for monitoring energy usage patterns in real-time. These visualizations helped users identify trends and anomalies in their energy consumption data.',
      'I optimized the UI/UX for better readability and engagement, ensuring users could easily interpret the presented data. The project applied data visualization techniques to make energy consumption information more accessible and actionable.',
    ],
  },

  {
    title: 'ARINC Microfids',
    slug: 'arinc-microfids',
    description:
      "ARINC, now part of Collins Aerospace (a Raytheon Technologies subsidiary), is an industry leader in aviation communications and information technology serving 80% of the world's airports. Their Microfids system provides real-time flight information displays for hotels and airport businesses globally.\n My responsibilities included frontend development and system integration, ensuring a seamless display of flight information through a Ruby on Rails backend.",
    image: 'https://gaboesquivel.com/images/work/arinc.png',
    tech: ['Ruby on Rails', 'AngularJS', 'Faye', 'LESS', 'Heroku'],
    type: ['contract', 'frontend'],
    achievements: [
      'Developed a real-time flight information display system.',
      'Integrated Ruby on Rails backend with AngularJS for seamless data updates.',
      'Optimized front-end performance for real-time user interaction.',
    ],
    story: [
      'ARINC Microfids is a flight information display system for hotels and airport businesses. It integrates with a Ruby on Rails backend. My responsibilities included frontend development and system integration, ensuring a seamless display of flight information.',
      'I integrated the Ruby on Rails backend with AngularJS to enable real-time data updates and user interaction. The system provides accurate and timely flight information to travelers.',
      'The implementation used Faye for real-time messaging and data synchronization. This project applied web development skills to create a practical information display system for the travel industry.',
    ],
  },
  {
    title: 'Capoeira Abolicao',
    slug: 'capoeira-abolicao',
    description:
      "Capoeira Abolição is a Brazilian martial arts group. I volunteered to create their promotional website, showcasing their professors and community.\n My involvement included website design and development, highlighting the group's activities and global presence.",
    link: 'https://capoieraabolicao.com',
    image: 'https://gaboesquivel.com/images/work/abolicao.jpg',
    tech: ['JavaScript', 'Wordpress', 'CSS', 'Bootstrap'],
    type: ['other', 'frontend'],
    achievements: [
      'Designed and developed a responsive website for Capoeira Abolição.',
      'Implemented interactive elements to showcase community events.',
      'Optimized site performance for a seamless user experience.',
    ],
    story: [
      "Capoeira Abolição is a Brazilian martial arts group. I volunteered to create their promotional website, showcasing their professors and community. My involvement included website design and development, highlighting the group's activities and global presence.",
      'I built a responsive website using JavaScript, WordPress, CSS, and Bootstrap to create an engaging online presence. The site featured interactive elements to highlight community events and Capoeira fundamentals.',
      'This volunteer project combined my web development skills with my personal involvement in the Capoeira community. The implementation served as a resource for both existing members and potential new students interested in the martial art.',
    ],
  },
  {
    title: 'Panini',
    slug: 'panini',
    description:
      'Panini, a project I worked on, provided a unique service or product in its field.\n My role in this project was focused on technical development and implementation.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/panini.jpg',
    tech: ['JavaScript', 'CSS', 'Wordpress'],
    type: ['other', 'frontend'],
    achievements: [
      "Developed and implemented the technical architecture for Panini's platform.",
      'Optimized website performance and ensured cross-browser compatibility.',
      'Enhanced UI/UX for a smooth and intuitive user experience.',
    ],
    story: [
      'Panini, a project I worked on, provided a unique service or product in its field. My role in this project was focused on technical development and implementation.',
      'I optimized website performance and ensured cross-browser compatibility for a consistent user experience. The work included UI/UX improvements to create an intuitive interface for better user engagement.',
      'This freelance project applied web development techniques to fulfill specific client requirements. The implementation delivered functional improvements while maintaining brand consistency.',
    ],
  },
  {
    title: 'Earth',
    slug: 'earth',
    description:
      'EARTH University offers education in agricultural sciences. I was responsible for building their main website, blog, and newsletter.\n My work involved creating a digital platform for information dissemination and community engagement, focusing on usability and content management.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/wordpress-earth-pai.jpg',
    tech: ['JavaScript', 'CSS', 'Wordpress'],
    type: ['other', 'frontend'],
    achievements: [
      "Developed a content management system for EARTH University's website.",
      'Designed a responsive and accessible blog for community engagement.',
      'Implemented newsletter automation for improved communication.',
    ],
    story: [
      'EARTH University offers education in agricultural sciences. I was responsible for building their main website, blog, and newsletter. My work involved creating a digital platform for information dissemination and community engagement, focusing on usability and content management.',
      'I implemented a content management system for efficient website updates and maintenance. This system allowed the university staff to manage their online presence without requiring technical expertise for routine content changes.',
      'The project included a responsive blog for community engagement and newsletter functionality for stakeholder communication. This work was completed while at IntergraphiDesign, my first job at a development shop, and applied web technologies to support an educational institution.',
    ],
  },
  {
    title: 'Proparques',
    slug: 'proparques',
    description:
      'ProParques is a nonprofit for national park sustainability. I developed their responsive landing page and an interactive national park map.\n My role included web design and development, focusing on user interaction and information accessibility for park exploration.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/proparques.jpg',
    tech: ['JavaScript', 'CSS', 'Wordpress'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed an interactive national park map for user exploration.',
      'Designed a responsive and informative landing page.',
      'Integrated user-friendly navigation for enhanced accessibility.',
    ],
    story: [
      'ProParques is a nonprofit for national park sustainability. I developed their responsive landing page and an interactive national park map. My role included web design and development, focusing on user interaction and information accessibility for park exploration.',
      'I created an interactive map for exploring various national parks, enhancing user understanding and appreciation of these resources. The map feature allowed visitors to learn about different parks and their unique characteristics.',
      "The implementation included a responsive landing page to ensure website accessibility across devices. This work was completed while at IntergraphiDesign, my first development job, and supported the organization's mission of promoting national park sustainability.",
    ],
  },
  {
    title: 'Fantasy Tennis',
    slug: 'fantasy-tennis',
    description:
      'FanSlam Fantasy Tennis is a strategic game for ATP, WTA, and Grand Slam tournaments. I designed and built both the frontend and backend.\n As a fullstack developer, my work encompassed creating an engaging and functional gaming experience, integrating strategy and user interface design.',
    link: 'https://www.fanslam.us',
    image: 'https://gaboesquivel.com/images/work/fantasy-tennis.jpg',
    tech: ['JavaScript', 'CSS'],
    type: ['contract', 'frontend', 'backend', 'fullstack'],
    achievements: [
      'Designed and developed a strategic fantasy tennis gaming platform.',
      'Built a responsive UI for seamless gameplay across devices.',
      'Integrated dynamic tournament data for real-time game updates.',
    ],
    story: [
      'FanSlam Fantasy Tennis is a strategic game for ATP, WTA, and Grand Slam tournaments. I designed and built both the frontend and backend. As a fullstack developer, my work encompassed creating an engaging and functional gaming experience, integrating strategy and user interface design.',
      'I developed a responsive UI for consistent gameplay across different devices and screen sizes. The implementation included dynamic tournament data integration for real-time game updates and results.',
      'This project combined sports statistics with game mechanics to create an interactive experience for tennis fans. The work required understanding both tennis tournament structures and effective game design principles.',
    ],
  },

  {
    title: 'Mobtion',
    slug: 'mobtion',
    description:
      'Mobtion agency specializes in mobile development services. I designed and developed their responsive website and WordPress CMS.\n My responsibilities included website design, development, and ensuring seamless content management for the agency.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/mobtion.jpg',
    tech: ['JavaScript', 'CSS', 'Wordpress', 'PHP'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed a responsive and modern website for Mobtion agency.',
      'Integrated WordPress CMS for efficient content management.',
      'Optimized website performance for improved loading speeds.',
    ],
    story: [
      'Mobtion agency specializes in mobile development services. I designed and developed their responsive website and WordPress CMS. My responsibilities included website design, development, and ensuring seamless content management for the agency.',
      "I created a modern and responsive website that effectively showcased their services and capabilities. The design focused on highlighting the agency's mobile development expertise and project portfolio.",
      'The implementation included WordPress CMS integration for efficient content management, allowing easy updates and maintenance. This work was completed while at IntergraphiDesign, my first development job, and delivered a functional web presence for a mobile development agency.',
    ],
  },
  {
    title: 'ITS',
    slug: 'its',
    description:
      'ITS InfoCom, an IT multinational, focuses on Remote Infrastructure Management. I implemented their primary website, CMS, and CRM integration.\n My role was to create and integrate digital solutions for the company, focusing on web presence and customer relationship management.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/website-its.jpg',
    tech: ['JavaScript', 'CSS', 'PHP', 'CMS'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed and deployed a company-wide CMS for ITS InfoCom.',
      'Integrated CRM solutions to streamline customer interactions.',
      'Optimized website architecture for scalability and security.',
    ],
    story: [
      'ITS InfoCom, an IT multinational, focuses on Remote Infrastructure Management. I implemented their primary website, CMS, and CRM integration. My role was to create and integrate digital solutions for the company, focusing on web presence and customer relationship management.',
      'I deployed a company-wide content management system for efficient website updates and maintenance. This implementation allowed staff to manage website content without requiring technical expertise for routine changes.',
      'The project included CRM integration to streamline customer interactions and data management. This work was completed while at IntergraphiDesign, my first development job, and delivered practical web solutions for a technology company.',
    ],
  },
  {
    title: 'Trivenzor',
    slug: 'trivenzor',
    description:
      'For Trivenzor, a hypertension medication, I developed a responsive landing page for patient and healthcare provider information.\n My work involved creating a user-friendly and informative digital platform, emphasizing medical information clarity and accessibility.',
    link: '#',
    image: 'https://gaboesquivel.com/images/work/tribenzor.jpg',
    tech: ['JavaScript', 'CSS', 'Mootools'],
    type: ['other', 'frontend'],
    achievements: [
      'Developed a fully responsive and accessible medical landing page.',
      'Ensured clarity and usability for both patients and healthcare providers.',
      'Optimized page speed and performance for better user engagement.',
    ],
    story: [
      'For Trivenzor, a hypertension medication, I developed a responsive landing page for patient and healthcare provider information. My work involved creating a user-friendly and informative digital platform, emphasizing medical information clarity and accessibility.',
      'I ensured the page was fully responsive and accessible, providing clear information for both patients and healthcare professionals. The implementation included performance optimization for improved load times and user engagement.',
      'This project required careful attention to medical content presentation and regulatory compliance. The design needed to balance visual appeal with accurate information delivery for a healthcare audience.',
    ],
  },
  {
    title: 'Living with Dryness',
    slug: 'living-with-dryness',
    description:
      "The Living with Dryness project involved crafting a responsive landing page focused on providing information and resources.\n As the developer, I ensured a pixel-perfect design and user-friendly navigation, catering to the project's specific audience and needs.",
    link: '#',
    image: 'https://gaboesquivel.com/images/work/living-with-dryness.jpg',
    tech: ['JavaScript', 'CSS', 'Wordpress'],
    type: ['other', 'frontend'],
    achievements: [
      'Designed and developed a responsive landing page for medical resources.',
      'Implemented a user-friendly navigation system for better accessibility.',
      'Optimized website layout for enhanced readability and engagement.',
    ],
    story: [
      "The Living with Dryness project involved crafting a responsive landing page focused on providing information and resources. As the developer, I ensured a pixel-perfect design and user-friendly navigation, catering to the project's specific audience and needs.",
      'I designed and developed a responsive landing page with valuable medical resources and implemented a user-friendly navigation system for better accessibility. The layout was optimized for readability and engagement.',
      'This project required balancing visual design with medical content presentation for a specific healthcare audience. The implementation focused on making medical information accessible and useful to the target users.',
    ],
  },
  {
    title: 'Costa Rica JS',
    slug: 'costa-rica-js',
    description:
      "Costa Rica JS, founded in 2010, grew to become Central America's largest JavaScript community with over 2000 developers. The community played a crucial role in fostering the region's tech ecosystem during the rise of Node.js, organizing major events like NodeSchool International Day and hosting speakers from companies like Mozilla and Netflix.\n As founder, I organized regular meetups, workshops, and the annual JSConf Costa Rica, helping establish Costa Rica as a growing tech hub in Latin America.",
    tech: ['JavaScript', 'NodeJS', 'ReactJS', 'TypeScript'],
    type: ['other', 'lead'],
    link: 'https://www.meetup.com/costaricajs/',
    image: 'https://gaboesquivel.com/images/bio/nodeschool-costa-rica.jpg',
    images: [
      'https://gaboesquivel.com/images/work/gaboesquivel-javascript-costarica.png',
      'https://gaboesquivel.com/images/gabo-workshop.jpg',
      'https://gaboesquivel.com/images/work/nodeschool.jpg',
      'https://gaboesquivel.com/images/work/nodeschool-1.jpg',
      'https://gaboesquivel.com/images/2016/05/paintballjs.jpg',
      'https://gaboesquivel.com/images/work/gaboesquivel-presentation.jpg',
    ],
    video: 'https://vimeo.com/167755778',
    achievements: [
      "Founded and grew Central America's largest JavaScript community to over 2000 developers.",
      'Organized regular meetups, workshops, and educational events.',
      "Fostered the region's tech ecosystem during the rise of Node.js and modern web frameworks.",
    ],
    story: [
      "Costa Rica JS became Central America's largest JavaScript community with over 2000 developers. The community played a crucial role in fostering the region's tech ecosystem as Node.js and modern web frameworks gained prominence.",
      'As founder, I organized regular meetups, workshops, and educational events to help developers learn emerging technologies and best practices. These activities supported professional development and knowledge sharing.',
      "The community served as a networking platform and career development resource for the region's tech sector. We focused on practical skills development through hands-on workshops and collaborative learning experiences.",
    ],
    related: [
      {
        url: 'https://gaboesquivel.com/blog/2016-06-nodeschool-international-day',
        title: 'NodeSchool International Day',
        publishedAt: '2016-06-01',
      },
      {
        url: 'https://gaboesquivel.com/blog/2015-5-paintball.js-recap',
        title: 'Paintball.js Recap',
        publishedAt: '2015-05-01',
      },
      {
        url: 'https://gaboesquivel.com/blog/2014-01-developing-software-in-costa-rica',
        title: 'Developing Software in Costa Rica',
        publishedAt: '2014-01-01',
      },
    ],
  },
  {
    title: 'AsoBlockchain',
    slug: 'asoblockchain',
    description:
      "AsoBlockchain, founded in 2017, is Costa Rica's first and leading non-profit blockchain association. The organization has trained over 1000 developers, partnered with major universities like ULACIT and ADEN Business School, and played a key role in shaping national cryptocurrency regulations through collaboration with the Central Bank and other regulatory bodies. Through initiatives like TicoBlockchain conference and CriptoCantina, it has become the primary driver of blockchain adoption in Central America.",
    tech: ['Ethereum', 'EOS', 'Antelope', 'Solidity', 'Polkadot', 'Substrate'],
    type: ['other', 'lead'],
    link: 'https://asoblockchain.org',
    image: 'https://gaboesquivel.com/images/2018/06/blockchain-costa-rica.jpg',
    images: [
      'https://gaboesquivel.com/images/work/ticoblockchain.jpg',
      'https://gaboesquivel.com/images/2019/02/ticoblockchain_eosio_workshop.jpg',
    ],
    video: 'https://www.youtube.com/watch?v=-1y0fGs8Xgw',
    achievements: [
      "Co-founded Costa Rica's first blockchain association in 2017.",
      'Established educational partnerships with ADEN International Business School and ULACIT.',
      'Created CriptoCantinaCR, a successful weekly educational and networking initiative.',
      "Organized TicoBlockchain, Costa Rica's premier blockchain conference.",
      'Developed advocacy programs for blockchain policy and regulation.',
      'Built a vibrant community supporting blockchain innovation and adoption.',
    ],
    story: [
      "AsoBlockchain is Costa Rica's leading non-profit blockchain association, focused on fostering trust, transparency, and innovation in the country's blockchain ecosystem. As a co-founder, I helped establish the organization's core principles and strategic direction.",
      'We developed initiatives like CriptoCantina and TicoBlockchain conference to create opportunities for education and community building. Our partnerships with institutions like ADEN Business School and ULACIT expanded access to specialized blockchain education.',
      "The association participates in policy discussions and regulatory frameworks to represent members' interests while promoting responsible blockchain adoption. Our work includes educational programs, industry partnerships, and community building.",
    ],
    related: [
      {
        url: 'https://gaboesquivel.com/blog/2019-03-ticoblockchain-2019-recap',
        title: 'TicoBlockchain 2019 Recap',
        publishedAt: '2019-03-01',
      },
      {
        url: 'https://gaboesquivel.com/blog/2019-01-international-crypto-conference-in-costa-rica',
        title: 'International Crypto Conference in Costa Rica',
        publishedAt: '2019-01-01',
      },
      {
        url: 'https://gaboesquivel.com/blog/2018-07-costa-rica-crypto-cantina',
        title: 'Costa Rica Crypto Cantina',
        publishedAt: '2018-07-01',
      },
      {
        url: 'https://gaboesquivel.com/blog/2018-06-blockchain-technology-in-costa-rica',
        title: 'Blockchain Technology in Costa Rica',
        publishedAt: '2018-06-01',
      },
    ],
  },
  {
    title: 'CryptoCantinaCR',
    slug: 'cryptocantinacr',
    description:
      "CryptoCantinaCR, established in September 2018, became Costa Rica's most influential blockchain community with over 500 regular participants and recognition from national media outlets like La Nación and El Financiero. What began as informal Thursday meetups has evolved into a formal educational initiative under CriptoCantina.org, which has trained hundreds of developers and influenced national cryptocurrency policy through engagement with government officials and regulators.",
    tech: ['Ethereum', 'EOS', 'Solidity', 'Antelope', 'Polkadot', 'Substrate'],
    type: ['other', 'lead'],
    link: 'https://criptocantina.org',
    image: 'https://gaboesquivel.com/images/work/cryptocantina.png',
    images: [
      'https://gaboesquivel.com/images/work/cryptocantina-multi.jpg',
      'https://gaboesquivel.com/images/work/cryptocantina-london-room-2.jpg',
      'https://gaboesquivel.com/images/work/cryptocantina-london-room.jpg',
      'https://gaboesquivel.com/images/work/cryptocantina-london-room-3.jpg',
      'https://gaboesquivel.com/images/work/cryptocantina-london-room-4.jpg',
    ],
    achievements: [
      'Established a recurring crypto community event every Thursday starting September 2018.',
      'Created an inclusive space for blockchain enthusiasts to connect and share knowledge.',
      'Built a forward-thinking community centered around blockchain and distributed consensus technologies.',
      'Facilitated networking between people from various backgrounds in the crypto space.',
      'Evolved into a formal educational platform promoting blockchain technology adoption.',
    ],
    story: [
      'CryptoCantinaCR started as a recurring after-office happy hour event that brought together blockchain, cryptography, and cryptocurrency enthusiasts in Costa Rica. What began as informal Thursday meetups at Central Pub in Paseo Colón has since evolved into a formal educational initiative under CriptoCantina.org.',
      'The events were designed to be casual and inclusive, with no presentations or formal talks, focusing on organic connections and discussions. This format created a space where participants could engage in meaningful conversations about blockchain technology.',
      'The initiative later evolved into CriptoCantina.org, a more structured educational platform led by Karla Córdoba. This organization now focuses on formal blockchain education, entrepreneur support, and helping newcomers enter the technology sector.',
    ],
    related: [
      {
        url: 'https://gaboesquivel.com/blog/2018-07-costa-rica-crypto-cantina',
        title: 'Costa Rica Crypto Cantina',
        publishedAt: '2018-07-01',
      },
    ],
  },
]
